name: secret
on: push
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    env:
      - name: Access secret
        run: echo "The secret value is ${{ secrets.APP_TOKEN}}"
    run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "APP_TOKEN is set for this job"
          else
            echo "APP_TOKEN is missing"
            exit 1
          fi      
